version: '3.7'

services:
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:9000
    volumes:
      - .:/var/www/html/

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
  
volumes:
  mysql-data: